development:
  adapter: postgresql
  database: landing-com3300_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: landing-com3300_test
  host: localhost
  min_messages: warning
  username: